### PR TITLE
Attribute command retry fix

### LINKED ISSUE #60: Attribute Command not working
# Describe the bug
When you try to use the `.attribute` command, you get:
`queue.filter is not a function`

It looks like Cypress removed the `.filter` method in version 8.3. I played with this locally and it *seems* to work if I just switch it to use `.find`

However, I think I'm missing something with the `invoked` 

# To Reproduce
Write any test that uses the `.attribute` command

# Expected behavior
The `.attribute` command should not throw an error.

# Versions and such:
 - OS: Windows 10
 - Cypress version: > 8.2
 - Cypress browser: Any
 - Cypress-commands version:  1.1.0

# Additional context
The problem line is here:
https://github.com/Lakitna/cypress-commands/blob/08adc6c31323e581c3d44e749f8327a52cb6365a/src/utils/commandQueue.js#L11

I cannot seem to find any info on the `.filter` method on Cypress docs or in the issues list.

I've seen the problem in Cypress 8.3 and 8.3.1

I can try to do a PR to fix it if that would help.

Thanks!

Ricardo Diaz

### PR DESCRIPTION
**Pull request by Lakitna**
Closes #60 

- [x] Tests
- [x] Documentation
- [x] Type definitions
- [x] Ready for merge

### CODE REVIEW

**Comment by Lakitna** [comment]
Will also close #54

**Comment by cubanx** [comment]
Sorry, not trying to harass, but can I help with this in any way? We want to move up to version 8.3+ of Cypress so we can get access to session stuff, but currently blocked.

If you don't think you can get to it within a week or so, I can do a fork of your code and work off that in the meantime.

Thanks so much for everything!

**Comment by Lakitna** [comment]
I had a week off last week, hence the delay. Merge is pending (self-) review right now.

I want to release this as part of `cypress-commands@2` (milestone https://github.com/Lakitna/cypress-commands/milestone/3) which will also include a breaking change for the order of `text()` (see #47)

**Comment by Lakitna** [comment]
@cubanx I just added the changelog with the breaking changes to this branch. You can start looking at potential changes you have to make ;)

I plan to take a last look at things tomorrow before I release it.

**Comment by cubanx** [comment]
Thanks so much! Really appreciate the work here, and if there's ever something you want me to work on let me know. I am not a super expert here, but I've been around the block a few times :)

**Pull request merged**
